name: Deploy to EC2 - backend

on:
  push:
    branches: [ master ]  

jobs:
  deploy:
    name: Deploy to AWS EC2 - backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with Docker Compose
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          cd ~/fyaar-backend

          echo "Pulling latest code.."
          git pull origin master


          echo "Stopping old containers.."
          sudo docker-compose down

          echo "Pruning unused Docker resources..."
          sudo docker system prune -af --volumes

          echo "Rebuilding and starting containers..."
          sudo docker-compose up -d --build
        EOF
